### ISSUE TITLE
Normalization for Tabula Muris documentation dataset is off-by-one

### ISSUE THREAD

**Issue by jacobkimmel** [chanzuckerberg/cellxgene-vignettes#1]
Hi CZI folks,

First -- thanks for the great resources!

I was playing with the Tabula Muris `anndata` object linked in the `cellxgene` documentation and noticed the normalization was a little funny.
The lowest count value in the dataset appears to be `0.69...`

```python
adata.X.min() # 0.6931472, a.k.a. ln(2)
```

I think the error may have originated in this notebook:

https://github.com/chanzuckerberg/cellxgene-compbio-methods/blob/master/dataset-processing/tabula-muris-processing.ipynb

During normalization, it looks like `1` was added to all counts before using `sc.pp.log1p`, which also adds one before applying the log transformation.

Thanks again!
Jacob

**Comment by ambrosejcarr** [comment]
Thanks for finding this, Jacob! I've removed the spurious duplication of += 1 during normalization.
